[env]
PATH = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.68
blur = true

option_as_alt = "Both"

[font]
#normal.family = "DejaVuSansM Nerd Font Mono"
normal.family = "0xProto Nerd Font Mono"
size = 14

